/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CreateAccountRouteImport } from './routes/create-account'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedDemandIndexRouteImport } from './routes/_authenticated/demand/index'
import { Route as AuthenticatedUserNameRouteImport } from './routes/_authenticated/user.$name'
import { Route as AuthenticatedDemandPropertiesRouteImport } from './routes/_authenticated/demand/properties'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateAccountRoute = CreateAccountRouteImport.update({
  id: '/create-account',
  path: '/create-account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDemandIndexRoute =
  AuthenticatedDemandIndexRouteImport.update({
    id: '/demand/',
    path: '/demand/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUserNameRoute = AuthenticatedUserNameRouteImport.update({
  id: '/user/$name',
  path: '/user/$name',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDemandPropertiesRoute =
  AuthenticatedDemandPropertiesRouteImport.update({
    id: '/demand/properties',
    path: '/demand/properties',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-account': typeof CreateAccountRoute
  '/login': typeof LoginRoute
  '/test': typeof TestRoute
  '/me': typeof AuthenticatedMeRoute
  '/users': typeof AuthenticatedUsersRoute
  '/demand/properties': typeof AuthenticatedDemandPropertiesRoute
  '/user/$name': typeof AuthenticatedUserNameRoute
  '/demand/': typeof AuthenticatedDemandIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-account': typeof CreateAccountRoute
  '/login': typeof LoginRoute
  '/test': typeof TestRoute
  '/me': typeof AuthenticatedMeRoute
  '/users': typeof AuthenticatedUsersRoute
  '/demand/properties': typeof AuthenticatedDemandPropertiesRoute
  '/user/$name': typeof AuthenticatedUserNameRoute
  '/demand': typeof AuthenticatedDemandIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/create-account': typeof CreateAccountRoute
  '/login': typeof LoginRoute
  '/test': typeof TestRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/demand/properties': typeof AuthenticatedDemandPropertiesRoute
  '/_authenticated/user/$name': typeof AuthenticatedUserNameRoute
  '/_authenticated/demand/': typeof AuthenticatedDemandIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-account'
    | '/login'
    | '/test'
    | '/me'
    | '/users'
    | '/demand/properties'
    | '/user/$name'
    | '/demand/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-account'
    | '/login'
    | '/test'
    | '/me'
    | '/users'
    | '/demand/properties'
    | '/user/$name'
    | '/demand'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/create-account'
    | '/login'
    | '/test'
    | '/_authenticated/me'
    | '/_authenticated/users'
    | '/_authenticated/demand/properties'
    | '/_authenticated/user/$name'
    | '/_authenticated/demand/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CreateAccountRoute: typeof CreateAccountRoute
  LoginRoute: typeof LoginRoute
  TestRoute: typeof TestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-account': {
      id: '/create-account'
      path: '/create-account'
      fullPath: '/create-account'
      preLoaderRoute: typeof CreateAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/demand/': {
      id: '/_authenticated/demand/'
      path: '/demand'
      fullPath: '/demand/'
      preLoaderRoute: typeof AuthenticatedDemandIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/user/$name': {
      id: '/_authenticated/user/$name'
      path: '/user/$name'
      fullPath: '/user/$name'
      preLoaderRoute: typeof AuthenticatedUserNameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/demand/properties': {
      id: '/_authenticated/demand/properties'
      path: '/demand/properties'
      fullPath: '/demand/properties'
      preLoaderRoute: typeof AuthenticatedDemandPropertiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedDemandPropertiesRoute: typeof AuthenticatedDemandPropertiesRoute
  AuthenticatedUserNameRoute: typeof AuthenticatedUserNameRoute
  AuthenticatedDemandIndexRoute: typeof AuthenticatedDemandIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedDemandPropertiesRoute: AuthenticatedDemandPropertiesRoute,
  AuthenticatedUserNameRoute: AuthenticatedUserNameRoute,
  AuthenticatedDemandIndexRoute: AuthenticatedDemandIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CreateAccountRoute: CreateAccountRoute,
  LoginRoute: LoginRoute,
  TestRoute: TestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
