/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CreateAccountRouteImport } from './routes/create-account'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsTermsRouteImport } from './routes/docs/terms'
import { Route as DocsGuideRouteImport } from './routes/docs/guide'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedSupplyIndexRouteImport } from './routes/_authenticated/supply/index'
import { Route as AuthenticatedDemandIndexRouteImport } from './routes/_authenticated/demand/index'
import { Route as AuthenticatedSupplyNewRouteImport } from './routes/_authenticated/supply/new'
import { Route as AuthenticatedDemandNewRouteImport } from './routes/_authenticated/demand/new'
import { Route as AuthenticatedDemandDemandIdRouteImport } from './routes/_authenticated/demand.$demandId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateAccountRoute = CreateAccountRouteImport.update({
  id: '/create-account',
  path: '/create-account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsTermsRoute = DocsTermsRouteImport.update({
  id: '/docs/terms',
  path: '/docs/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsGuideRoute = DocsGuideRouteImport.update({
  id: '/docs/guide',
  path: '/docs/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSupplyIndexRoute =
  AuthenticatedSupplyIndexRouteImport.update({
    id: '/supply/',
    path: '/supply/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDemandIndexRoute =
  AuthenticatedDemandIndexRouteImport.update({
    id: '/demand/',
    path: '/demand/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSupplyNewRoute = AuthenticatedSupplyNewRouteImport.update({
  id: '/supply/new',
  path: '/supply/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDemandNewRoute = AuthenticatedDemandNewRouteImport.update({
  id: '/demand/new',
  path: '/demand/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDemandDemandIdRoute =
  AuthenticatedDemandDemandIdRouteImport.update({
    id: '/demand/$demandId',
    path: '/demand/$demandId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-account': typeof CreateAccountRoute
  '/login': typeof LoginRoute
  '/me': typeof AuthenticatedMeRoute
  '/docs/guide': typeof DocsGuideRoute
  '/docs/terms': typeof DocsTermsRoute
  '/docs/': typeof DocsIndexRoute
  '/demand/$demandId': typeof AuthenticatedDemandDemandIdRoute
  '/demand/new': typeof AuthenticatedDemandNewRoute
  '/supply/new': typeof AuthenticatedSupplyNewRoute
  '/demand/': typeof AuthenticatedDemandIndexRoute
  '/supply/': typeof AuthenticatedSupplyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-account': typeof CreateAccountRoute
  '/login': typeof LoginRoute
  '/me': typeof AuthenticatedMeRoute
  '/docs/guide': typeof DocsGuideRoute
  '/docs/terms': typeof DocsTermsRoute
  '/docs': typeof DocsIndexRoute
  '/demand/$demandId': typeof AuthenticatedDemandDemandIdRoute
  '/demand/new': typeof AuthenticatedDemandNewRoute
  '/supply/new': typeof AuthenticatedSupplyNewRoute
  '/demand': typeof AuthenticatedDemandIndexRoute
  '/supply': typeof AuthenticatedSupplyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/create-account': typeof CreateAccountRoute
  '/login': typeof LoginRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/docs/guide': typeof DocsGuideRoute
  '/docs/terms': typeof DocsTermsRoute
  '/docs/': typeof DocsIndexRoute
  '/_authenticated/demand/$demandId': typeof AuthenticatedDemandDemandIdRoute
  '/_authenticated/demand/new': typeof AuthenticatedDemandNewRoute
  '/_authenticated/supply/new': typeof AuthenticatedSupplyNewRoute
  '/_authenticated/demand/': typeof AuthenticatedDemandIndexRoute
  '/_authenticated/supply/': typeof AuthenticatedSupplyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-account'
    | '/login'
    | '/me'
    | '/docs/guide'
    | '/docs/terms'
    | '/docs/'
    | '/demand/$demandId'
    | '/demand/new'
    | '/supply/new'
    | '/demand/'
    | '/supply/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-account'
    | '/login'
    | '/me'
    | '/docs/guide'
    | '/docs/terms'
    | '/docs'
    | '/demand/$demandId'
    | '/demand/new'
    | '/supply/new'
    | '/demand'
    | '/supply'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/create-account'
    | '/login'
    | '/_authenticated/me'
    | '/docs/guide'
    | '/docs/terms'
    | '/docs/'
    | '/_authenticated/demand/$demandId'
    | '/_authenticated/demand/new'
    | '/_authenticated/supply/new'
    | '/_authenticated/demand/'
    | '/_authenticated/supply/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CreateAccountRoute: typeof CreateAccountRoute
  LoginRoute: typeof LoginRoute
  DocsGuideRoute: typeof DocsGuideRoute
  DocsTermsRoute: typeof DocsTermsRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-account': {
      id: '/create-account'
      path: '/create-account'
      fullPath: '/create-account'
      preLoaderRoute: typeof CreateAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/terms': {
      id: '/docs/terms'
      path: '/docs/terms'
      fullPath: '/docs/terms'
      preLoaderRoute: typeof DocsTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/guide': {
      id: '/docs/guide'
      path: '/docs/guide'
      fullPath: '/docs/guide'
      preLoaderRoute: typeof DocsGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/supply/': {
      id: '/_authenticated/supply/'
      path: '/supply'
      fullPath: '/supply/'
      preLoaderRoute: typeof AuthenticatedSupplyIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/demand/': {
      id: '/_authenticated/demand/'
      path: '/demand'
      fullPath: '/demand/'
      preLoaderRoute: typeof AuthenticatedDemandIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/supply/new': {
      id: '/_authenticated/supply/new'
      path: '/supply/new'
      fullPath: '/supply/new'
      preLoaderRoute: typeof AuthenticatedSupplyNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/demand/new': {
      id: '/_authenticated/demand/new'
      path: '/demand/new'
      fullPath: '/demand/new'
      preLoaderRoute: typeof AuthenticatedDemandNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/demand/$demandId': {
      id: '/_authenticated/demand/$demandId'
      path: '/demand/$demandId'
      fullPath: '/demand/$demandId'
      preLoaderRoute: typeof AuthenticatedDemandDemandIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedDemandDemandIdRoute: typeof AuthenticatedDemandDemandIdRoute
  AuthenticatedDemandNewRoute: typeof AuthenticatedDemandNewRoute
  AuthenticatedSupplyNewRoute: typeof AuthenticatedSupplyNewRoute
  AuthenticatedDemandIndexRoute: typeof AuthenticatedDemandIndexRoute
  AuthenticatedSupplyIndexRoute: typeof AuthenticatedSupplyIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedDemandDemandIdRoute: AuthenticatedDemandDemandIdRoute,
  AuthenticatedDemandNewRoute: AuthenticatedDemandNewRoute,
  AuthenticatedSupplyNewRoute: AuthenticatedSupplyNewRoute,
  AuthenticatedDemandIndexRoute: AuthenticatedDemandIndexRoute,
  AuthenticatedSupplyIndexRoute: AuthenticatedSupplyIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CreateAccountRoute: CreateAccountRoute,
  LoginRoute: LoginRoute,
  DocsGuideRoute: DocsGuideRoute,
  DocsTermsRoute: DocsTermsRoute,
  DocsIndexRoute: DocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
